<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath /> <!-- lookup parent from repository -->
    </parent>
	<groupId>de.peterspace.cardano</groupId>
	<artifactId>cardano-java-lib</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	
	<!-- mvn -N wrapper:wrapper -Dmaven=3.9.14 -->
	<!-- mvn versions:update-properties -->
	<properties>
		<bitcoinj.version>0.17.1</bitcoinj.version>
		<spotless-maven-plugin.version>3.10.2</spotless-maven-plugin.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.bitcoinj</groupId>
			<artifactId>bitcoinj-core</artifactId>
			<version>${bitcoinj.version}</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	 <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>

            <!-- Spotless - enforce uniform code formatting -->
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless-maven-plugin.version}</version>
                <configuration>
                    <java>
                        <includes>
                            <include>src/main/java/**/*.java</include>
                            <include>src/test/java/**/*.java</include>
                        </includes>
                        <cleanthat />
                        <googleJavaFormat />
                    </java>
                    <yaml>
                        <includes>
                            <include>src/main/resources/**/*.yaml</include>
                        </includes>
                        <prettier />
                    </yaml>
                    <json>
                        <includes>
                            <include>.devcontainer/devcontainer.json</include>
                        </includes>
                        <prettier />
                    </json>
                    <formats>
                        <format>
                            <includes>
                                <include>pom.xml</include>
                            </includes>
                            <eclipseWtp>
                                <type>XML</type>
                                <files>.eclipseWtp.prefs</files>
                            </eclipseWtp>
                        </format>
                    </formats>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>